name: Deploy to Shared Hosting (FTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, pdo_mysql, bcmath, zip, curl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm ci --no-audit --no-fund

      - name: Build assets
        run: npm run build

      - name: Cleanup files not needed on server
        run: |
          rm -rf .git
          rm -rf tests
          rm -rf node_modules
          rm -rf .github

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          # Contoh InfinityFree: /htdocs/ atau /yourdomain.com/htdocs/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.github/**
            **/tests/**
            **/node_modules/**
            storage/framework/cache/data/**
            storage/logs/**
            .env


